name: 'Create Pull Request'
description: 'Create a Pull Request'
inputs:
  directory:
    description: 'Directory name'
    required: true
  branch-name:
    description: 'Branch name'
    required: true
  commit-message:
    description: 'Commit message'
    required: true
  title:
    description: 'PR title'
    required: true
  description:
    description: 'PR description'
    required: false
    default: ''
  draft:
    description: 'Create a Draft PR'
    required: false
    default: 'false'
  token:
    description: 'Personal Access Token'
    required: false
    default: ${{ github.token }}
outputs:
  new-pr-url:
    description: 'URL of Created PR'
    value: ${{ steps.pull-request.outputs.PR_URL }}
    
runs:
  using: "composite"
  steps:
    - name: Set Draft
      id: set-draft
      run: |
        if [ '${{ inputs.draft }}' = 'true' ]; then
          echo 'DRAFT="--draft"' >> $GITHUB_OUTPUT
        else
          echo 'DRAFT=""' >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Create Pull Request
      id: pull-request
      run: |  
        git checkout -b ${{ inputs.branch-name }}
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
        git commit -am "${{ inputs.commit-message }}"
        git push -u origin ${{ inputs.branch-name }}
        echo "PR_URL=$(gh pr create --title "${{ inputs.title }}" --body "${{ inputs.description }}" ${{ steps.set-draft.outputs.DRAFT }})" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      working-directory: ${{ inputs.directory }}
      shell: bash
